name: 'remove-old-releases'
description: 'This action removes old releases from github based on rules'
author: 'Stephen Reindl'
branding:
  icon: 'trash-2'
  color: 'orange'
inputs:
  tasks:
    required: true
    description: 'The tasks to be performed'
    default: ''
  token:
    required: true
    description: 'The guthub token to be used, e.g. github.TOKEN'
    default: ''
  dry-run:
    required: false
    description: 'If true, no actions are performed. Default is: true for savety reasons'
    default: true
runs:
  using: 'node16'
  main: 'dist/index.js'
