name: 'remove-old-releases'
description: 'This action removes old releases from github based on rules'
author: 'Stephen Reindl'
inputs:
  tasks:
    required: true
    description: 'The tasks to be performed'
    default: ''
  token:
    required: true
    description: 'The guthub token to be used, e.g. github.TOKEN'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
